void METvarBinDataMC_LL()
{
//=========Macro generated from canvas: METvarBinDataMC_LL/METvarBinDataMC_LL
//=========  (Thu Feb  8 23:25:31 2018) by ROOT version6.10/02
   TCanvas *METvarBinDataMC_LL = new TCanvas("METvarBinDataMC_LL", "METvarBinDataMC_LL",100,100,1500,800);
   gStyle->SetOptStat(0);
   METvarBinDataMC_LL->Range(0,0,1,1);
   METvarBinDataMC_LL->SetFillColor(0);
   METvarBinDataMC_LL->SetBorderMode(0);
   METvarBinDataMC_LL->SetBorderSize(2);
   METvarBinDataMC_LL->SetGridx();
   METvarBinDataMC_LL->SetGridy();
   METvarBinDataMC_LL->SetTickx(1);
   METvarBinDataMC_LL->SetTicky(1);
   METvarBinDataMC_LL->SetLeftMargin(0.12);
   METvarBinDataMC_LL->SetRightMargin(0.12);
   METvarBinDataMC_LL->SetBottomMargin(0.12);
   METvarBinDataMC_LL->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: METvarBinDataMC_LLtop
   TPad *METvarBinDataMC_LLtop = new TPad("METvarBinDataMC_LLtop", "METvarBinDataMC_LLtop",0,0.4,1,1);
   METvarBinDataMC_LLtop->Draw();
   METvarBinDataMC_LLtop->cd();
   METvarBinDataMC_LLtop->Range(-142.1053,-0.5332907,1042.105,1.566732);
   METvarBinDataMC_LLtop->SetFillColor(0);
   METvarBinDataMC_LLtop->SetBorderMode(0);
   METvarBinDataMC_LLtop->SetBorderSize(2);
   METvarBinDataMC_LLtop->SetLogy();
   METvarBinDataMC_LLtop->SetGridx();
   METvarBinDataMC_LLtop->SetGridy();
   METvarBinDataMC_LLtop->SetTickx(1);
   METvarBinDataMC_LLtop->SetTicky(1);
   METvarBinDataMC_LLtop->SetLeftMargin(0.12);
   METvarBinDataMC_LLtop->SetRightMargin(0.12);
   METvarBinDataMC_LLtop->SetBottomMargin(0);
   METvarBinDataMC_LLtop->SetFrameBorderMode(0);
   METvarBinDataMC_LLtop->SetFrameBorderMode(0);
   Double_t xAxis1[10] = {0, 100, 125, 160, 200, 270, 350, 450, 750, 900}; 
   
   TH1D *METvarBin__1 = new TH1D("METvarBin__1","",9, xAxis1);
   METvarBin__1->SetBinContent(2,6);
   METvarBin__1->SetBinContent(3,9);
   METvarBin__1->SetBinContent(4,4);
   METvarBin__1->SetBinContent(5,7);
   METvarBin__1->SetBinContent(6,2);
   METvarBin__1->SetBinContent(7,6);
   METvarBin__1->SetBinContent(8,2);
   METvarBin__1->SetBinError(2,2.44949);
   METvarBin__1->SetBinError(3,3);
   METvarBin__1->SetBinError(4,2);
   METvarBin__1->SetBinError(5,2.645751);
   METvarBin__1->SetBinError(6,1.414214);
   METvarBin__1->SetBinError(7,2.44949);
   METvarBin__1->SetBinError(8,1.414214);
   METvarBin__1->SetEntries(37);
   METvarBin__1->SetStats(0);
   METvarBin__1->SetLineWidth(2);
   METvarBin__1->SetMarkerStyle(20);
   METvarBin__1->GetXaxis()->SetRange(1,9);
   METvarBin__1->GetXaxis()->SetLabelFont(42);
   METvarBin__1->GetXaxis()->SetLabelSize(0.05);
   METvarBin__1->GetXaxis()->SetTitleSize(0.05);
   METvarBin__1->GetXaxis()->SetTitleFont(42);
   METvarBin__1->GetYaxis()->SetTitle("Events");
   METvarBin__1->GetYaxis()->SetNdivisions(2);
   METvarBin__1->GetYaxis()->SetLabelFont(42);
   METvarBin__1->GetYaxis()->SetLabelSize(0.09);
   METvarBin__1->GetYaxis()->SetTitleSize(0.09);
   METvarBin__1->GetYaxis()->SetTitleOffset(0.45);
   METvarBin__1->GetYaxis()->SetTitleFont(42);
   METvarBin__1->GetZaxis()->SetLabelFont(42);
   METvarBin__1->GetZaxis()->SetLabelSize(0.05);
   METvarBin__1->GetZaxis()->SetTitleSize(0.05);
   METvarBin__1->GetZaxis()->SetTitleFont(42);
   METvarBin__1->Draw("E1");
   Double_t xAxis2[10] = {0, 100, 125, 160, 200, 270, 350, 450, 750, 900}; 
   
   TH1D *METvarBin__2 = new TH1D("METvarBin__2","MET with variable bin size",9, xAxis2);
   METvarBin__2->SetBinContent(2,4.785299);
   METvarBin__2->SetBinContent(3,5.865632);
   METvarBin__2->SetBinContent(4,6.447946);
   METvarBin__2->SetBinContent(5,6.937781);
   METvarBin__2->SetBinContent(6,4.277719);
   METvarBin__2->SetBinContent(7,3.991755);
   METvarBin__2->SetBinContent(8,4.438602);
   METvarBin__2->SetBinContent(9,0.9958853);
   METvarBin__2->SetBinContent(10,0.4604567);
   METvarBin__2->SetBinError(2,0.3575323);
   METvarBin__2->SetBinError(3,0.3845078);
   METvarBin__2->SetBinError(4,1.018068);
   METvarBin__2->SetBinError(5,0.9884986);
   METvarBin__2->SetBinError(6,0.346234);
   METvarBin__2->SetBinError(7,0.5472112);
   METvarBin__2->SetBinError(8,0.3646887);
   METvarBin__2->SetBinError(9,0.3001503);
   METvarBin__2->SetBinError(10,0.09593717);
   METvarBin__2->SetEntries(4675);
   METvarBin__2->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ff3366");
   METvarBin__2->SetLineColor(ci);
   METvarBin__2->SetLineWidth(2);

   ci = TColor::GetColor("#ff3366");
   METvarBin__2->SetMarkerColor(ci);
   METvarBin__2->SetMarkerStyle(21);
   METvarBin__2->GetXaxis()->SetRange(1,9);
   METvarBin__2->GetXaxis()->SetLabelFont(42);
   METvarBin__2->GetXaxis()->SetLabelSize(0.05);
   METvarBin__2->GetXaxis()->SetTitleSize(0.05);
   METvarBin__2->GetXaxis()->SetTitleFont(42);
   METvarBin__2->GetYaxis()->SetLabelFont(42);
   METvarBin__2->GetYaxis()->SetLabelSize(0.05);
   METvarBin__2->GetYaxis()->SetTitleSize(0.05);
   METvarBin__2->GetYaxis()->SetTitleOffset(0);
   METvarBin__2->GetYaxis()->SetTitleFont(42);
   METvarBin__2->GetZaxis()->SetLabelFont(42);
   METvarBin__2->GetZaxis()->SetLabelSize(0.05);
   METvarBin__2->GetZaxis()->SetTitleSize(0.05);
   METvarBin__2->GetZaxis()->SetTitleFont(42);
   METvarBin__2->Draw("E1 same");
   
   TLegend *leg = new TLegend(0.7,0.65,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("METvarBin","Data","elp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("METvarBin","MC","elp");

   ci = TColor::GetColor("#ff3366");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);

   ci = TColor::GetColor("#ff3366");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis3[10] = {0, 100, 125, 160, 200, 270, 350, 450, 750, 900}; 
   
   TH1D *METvarBin_copy__3 = new TH1D("METvarBin_copy__3","",9, xAxis3);
   METvarBin_copy__3->SetBinContent(2,6);
   METvarBin_copy__3->SetBinContent(3,9);
   METvarBin_copy__3->SetBinContent(4,4);
   METvarBin_copy__3->SetBinContent(5,7);
   METvarBin_copy__3->SetBinContent(6,2);
   METvarBin_copy__3->SetBinContent(7,6);
   METvarBin_copy__3->SetBinContent(8,2);
   METvarBin_copy__3->SetBinError(2,2.44949);
   METvarBin_copy__3->SetBinError(3,3);
   METvarBin_copy__3->SetBinError(4,2);
   METvarBin_copy__3->SetBinError(5,2.645751);
   METvarBin_copy__3->SetBinError(6,1.414214);
   METvarBin_copy__3->SetBinError(7,2.44949);
   METvarBin_copy__3->SetBinError(8,1.414214);
   METvarBin_copy__3->SetEntries(37);
   METvarBin_copy__3->SetDirectory(0);
   METvarBin_copy__3->SetStats(0);
   METvarBin_copy__3->SetLineWidth(2);
   METvarBin_copy__3->SetMarkerStyle(20);
   METvarBin_copy__3->GetXaxis()->SetRange(1,9);
   METvarBin_copy__3->GetXaxis()->SetLabelFont(42);
   METvarBin_copy__3->GetXaxis()->SetLabelSize(0.05);
   METvarBin_copy__3->GetXaxis()->SetTitleSize(0.05);
   METvarBin_copy__3->GetXaxis()->SetTitleFont(42);
   METvarBin_copy__3->GetYaxis()->SetTitle("Events");
   METvarBin_copy__3->GetYaxis()->SetNdivisions(2);
   METvarBin_copy__3->GetYaxis()->SetLabelFont(42);
   METvarBin_copy__3->GetYaxis()->SetLabelSize(0.09);
   METvarBin_copy__3->GetYaxis()->SetTitleSize(0.09);
   METvarBin_copy__3->GetYaxis()->SetTitleOffset(0.45);
   METvarBin_copy__3->GetYaxis()->SetTitleFont(42);
   METvarBin_copy__3->GetZaxis()->SetLabelFont(42);
   METvarBin_copy__3->GetZaxis()->SetLabelSize(0.05);
   METvarBin_copy__3->GetZaxis()->SetTitleSize(0.05);
   METvarBin_copy__3->GetZaxis()->SetTitleFont(42);
   METvarBin_copy__3->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.12,0.91,"CMS #it{#bf{Simulation}}");
tex->SetNDC();
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.73,0.91,"#bf{35.9 fb^{-1}(13TeV)}");
tex->SetNDC();
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   METvarBinDataMC_LLtop->Modified();
   METvarBinDataMC_LL->cd();
  
// ------------>Primitives in pad: METvarBinDataMC_LLbot
   TPad *METvarBinDataMC_LLbot = new TPad("METvarBinDataMC_LLbot", "METvarBinDataMC_LLbot",0,0,1,0.4);
   METvarBinDataMC_LLbot->Draw();
   METvarBinDataMC_LLbot->cd();
   METvarBinDataMC_LLbot->Range(-142.1053,-1.056154,1042.105,1.99);
   METvarBinDataMC_LLbot->SetFillColor(0);
   METvarBinDataMC_LLbot->SetBorderMode(0);
   METvarBinDataMC_LLbot->SetBorderSize(2);
   METvarBinDataMC_LLbot->SetGridx();
   METvarBinDataMC_LLbot->SetGridy();
   METvarBinDataMC_LLbot->SetTickx(1);
   METvarBinDataMC_LLbot->SetTicky(1);
   METvarBinDataMC_LLbot->SetLeftMargin(0.12);
   METvarBinDataMC_LLbot->SetRightMargin(0.12);
   METvarBinDataMC_LLbot->SetTopMargin(0);
   METvarBinDataMC_LLbot->SetBottomMargin(0.35);
   METvarBinDataMC_LLbot->SetFrameBorderMode(0);
   METvarBinDataMC_LLbot->SetFrameBorderMode(0);
   Double_t xAxis4[10] = {0, 100, 125, 160, 200, 270, 350, 450, 750, 900}; 
   
   TH1D *Ratio_NuNuToLL__4 = new TH1D("Ratio_NuNuToLL__4","",9, xAxis4);
   Ratio_NuNuToLL__4->SetBinContent(2,1.25384);
   Ratio_NuNuToLL__4->SetBinContent(3,1.534362);
   Ratio_NuNuToLL__4->SetBinContent(4,0.6203526);
   Ratio_NuNuToLL__4->SetBinContent(5,1.008968);
   Ratio_NuNuToLL__4->SetBinContent(6,0.4675388);
   Ratio_NuNuToLL__4->SetBinContent(7,1.503098);
   Ratio_NuNuToLL__4->SetBinContent(8,0.4505923);
   Ratio_NuNuToLL__4->SetBinError(2,0.5203799);
   Ratio_NuNuToLL__4->SetBinError(3,0.5212501);
   Ratio_NuNuToLL__4->SetBinError(4,0.3252739);
   Ratio_NuNuToLL__4->SetBinError(5,0.4075505);
   Ratio_NuNuToLL__4->SetBinError(6,0.3327586);
   Ratio_NuNuToLL__4->SetBinError(7,0.6473087);
   Ratio_NuNuToLL__4->SetBinError(8,0.3207606);
   Ratio_NuNuToLL__4->SetMinimum(0.01);
   Ratio_NuNuToLL__4->SetMaximum(1.99);
   Ratio_NuNuToLL__4->SetEntries(32.32055);
   Ratio_NuNuToLL__4->SetStats(0);
   Ratio_NuNuToLL__4->SetLineWidth(2);
   Ratio_NuNuToLL__4->SetMarkerStyle(20);
   Ratio_NuNuToLL__4->GetXaxis()->SetTitle("p_{T}^{miss}(GeV)");
   Ratio_NuNuToLL__4->GetXaxis()->SetRange(1,9);
   Ratio_NuNuToLL__4->GetXaxis()->SetLabelFont(42);
   Ratio_NuNuToLL__4->GetXaxis()->SetLabelSize(0.15);
   Ratio_NuNuToLL__4->GetXaxis()->SetTitleSize(0.16);
   Ratio_NuNuToLL__4->GetXaxis()->SetTitleOffset(0.9);
   Ratio_NuNuToLL__4->GetXaxis()->SetTitleFont(42);
   Ratio_NuNuToLL__4->GetYaxis()->SetTitle("#frac{Data}{MC}");
   Ratio_NuNuToLL__4->GetYaxis()->SetNdivisions(505);
   Ratio_NuNuToLL__4->GetYaxis()->SetLabelFont(42);
   Ratio_NuNuToLL__4->GetYaxis()->SetLabelSize(0.14);
   Ratio_NuNuToLL__4->GetYaxis()->SetTitleSize(0.13);
   Ratio_NuNuToLL__4->GetYaxis()->SetTitleOffset(0.35);
   Ratio_NuNuToLL__4->GetYaxis()->SetTitleFont(42);
   Ratio_NuNuToLL__4->GetZaxis()->SetLabelFont(42);
   Ratio_NuNuToLL__4->GetZaxis()->SetLabelSize(0.05);
   Ratio_NuNuToLL__4->GetZaxis()->SetTitleSize(0.05);
   Ratio_NuNuToLL__4->GetZaxis()->SetTitleFont(42);
   Ratio_NuNuToLL__4->Draw("e1");
   METvarBinDataMC_LLbot->Modified();
   METvarBinDataMC_LL->cd();
   METvarBinDataMC_LL->Modified();
   METvarBinDataMC_LL->cd();
   METvarBinDataMC_LL->SetSelected(METvarBinDataMC_LL);
}
